
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">


<style>
    body {
        background-image: url('public/images/velo5.jpg');
        background-size: cover;
        }
</style>


<h1 class="text-center mt-5">Bienvenue sur la pédale joyeuse !<h1>


<?php

    if(empty($_SESSION['id'])){
?>

<div class="container d-flex align-items-center" style="height: 550px;">
    <div class="container col-sm-12 col-md-8 col-lg-3 border border-danger shadow-lg mb-5">
        <div class="row shadow-lg bg-info-rounded">
            <div class="text-center mt-4">
                    <h2 class="text-center">Connexion</h2>
                    <form class="form-group" method="POST" action="Utils\connexion">
                         <div class="d-grid gap-2 mx-auto mt-4">
 
                            <input type="nom" name="prenom" class="form-control text-center" placeholder="Prénom" required="required" autocomplete="off">
                            <input type="password" name="pass" class="form-control text-center" placeholder="Mot de passe" required="required" autocomplete="off">
                        
                        </div>
                        <div class="d-grid gap-2 col-6 mx-auto mt-4">
                            <button tpe="submit" class="btn btn-danger mb-4">Connexion</button>
                        </div>
                    </form>
                    
            </div>
        </div>
    </div>
</div>

<?php
}else{
?>
        <div class="container mt-5 mb-5 text-center">
             <div class ="fs-4 mb-3"> Vous êtes déja connecté en tant que <?= $_SESSION["prenom"] ?></div>
            <a href="Utils/deconnexion">Déconnexion</a>
        </div>

<?php
}
?>


</body>
</html>