

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>
    <base href="http://localhost/velo/">
    <!-- Ici on a pas besoin de sortir du dossier views avec ../ car on est dans index qui a fait require de base.phtml. donc si nous 
    sommes sur index : on a pas besoin de sortir du dossier mais d'y aller direct -->
    <link rel="stylesheet" href="public/Base.css">

    <!-- lien bootstrap : -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- lien bootstrap icons -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
     <!-- 3 Liens jquery js pour le modal de confirmation de suppression -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
</head>
<body>

<!-- Un .phtml = un php sur lequel on lui dit qu'on mettra due l' html -->


<nav class="navbar navbar-expand-lg bg-body-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="">Connexion</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <?php if(!isset($_SESSION["id"]) || $_SESSION["id_role"] == 'boss'){ ?> <a class="nav-link" href="Admin/showPersonnels">Personnels</a> <?php } ?>
        </li>
        <li class="nav-item">
        <?php if(!isset($_SESSION["id"]) || $_SESSION["id_role"] == 'boss'){ ?> <a class="nav-link" href="Admin/createPersonnel">Personnel<i class="bi bi-tools"></i></a> <?php } ?>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Stock/showStock">Stock</a>
        </li>
        <li class="nav-item">
          <?php if(!isset($_SESSION["id"]) || $_SESSION["id_role"] == 'boss'){ ?> <a class="nav-link" href ="Stock/createStock">Stock<i class="bi bi-tools"></i> </a> <?php } ?>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Client/showClient">Clients</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Client/createClient">Client<i class="bi bi-tools"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Factures</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Factures++</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Admin/showChiffres">Chiffres</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Utils/deconnexion">Déconnexion</a>
        </li>
      </ul>
    </div>
  </div>
</nav>



<main>
    <?php  require_once $page; ?>
</main>


<!-- lien bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
 

</body>
</html>