

public function showChiffres(){

$data = new Patron();
$salesOfTheDay = $data->getSalesOfTheDay();
$salesOfStockOfTheMonth = $data->getSalesOfStockOfTheMonth();
$SalesOfStockOfTheMonthAndShowTVA = $data->getSalesOfStockOfTheMonthAndShowTVA();
$SalesOfStockOfTheYear = $data->getSalesOfStockOfTheYear();
$SalesByEmployeesByMonth = $data->getSalesByEmployeesByMonth();
$SalesByEmployeesByYear = $data->getSalesByEmployeesByYear();

A RAJOUTER :
                                    $data = new Employee();
                                    $SalesOfTheMonth = $data->getSalesOfTheMonth($id);
                                    $SalesOfTheYear = $data->getSalesOfTheYear($id);
                                    $createInvoice = $data->createInvoice($id);

$page = "views/Chiffres.phtml";
 
require_once "views/Base.phtml";
}



<div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Récapitulatif mensuel des ventes du mois pour $_SESSION['prenom'] :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">ID Facture</th>
                        <th scope="col">Date</th>
                        <th scope="col">Total_ht</th>
                        <th scope="col">Total_ttc</th>
                        <th scope="col">Id_client</th>
                        <th scope="col">Id_personnel</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfTheMonth as $saleso) {
                        echo '<tr>
                                <td> '.$saleso['id'].'</td>
                                <td> '.$saleso['dateFact'].'</td>
                                <td> '.$saleso['prix_ht'].'</td>
                                <td> '.$saleso['prix_ttc'].'</td>
                                <td> '.$saleso['id_client'].'</td>
                                <td> '.$saleso['id_personnel'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>




    

    <div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Récapitulatif mensuel des ventes de l'année pour $_SESSION['prenom'] :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">ID Facture</th>
                        <th scope="col">Date</th>
                        <th scope="col">Total_ht</th>
                        <th scope="col">Total_ttc</th>
                        <th scope="col">Id_client</th>
                        <th scope="col">Id_personnel</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfTheYear as $sale) {
                        echo '<tr>
                                <td> '.$sale['id'].'</td>
                                <td> '.$sale['dateFact'].'</td>
                                <td> '.$sale['prix_ht'].'</td>
                                <td> '.$sale['prix_ttc'].'</td>
                                <td> '.$sale['id_client'].'</td>
                                <td> '.$sale['id_personnel'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>
