


// if employee session (il faudra a la connexion session start recuperer le prenom):


    Aller chercher les 2 tableaux une fois la session start créer dans la feuille : chiffres2.phtml




// else : session patron :


 
<?php
foreach($salesOfTheDay as $sal)
echo' 
<p class="text-center mt-5">Le total des ventes du jour est : '.$sal['Total'].' €</p>
';
?>





<div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Récapitulatif mensuel des ventes par produit :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">ID Produit</th>
                        <th scope="col">Désignation</th>
                        <th scope="col">Quantité vendue</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($salesOfStockOfTheMonth as $sales) {
                        echo '<tr>
                                <td> '.$sales['id_produits'].'</td>
                                <td> '.$sales['designation'].'</td>
                                <td> '.$sales['SUM(quantite)'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>





    
<div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Total TVA collecté par mois :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Total_ht</th>
                        <th scope="col">Total_ttc</th>
                        <th scope="col">TVA à reverser</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfStockOfTheMonthAndShowTVA as $salesof) {
                        echo '<tr>
                                <td> '.$salesof['total_ht'].'</td>
                                <td> '.$salesof['total_ttc'].'</td>
                                <td> '.$salesof['TVA_a_reverser'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>





    
    
<div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Etat cumulé des ventes par produit depuis le premier janvier de l’année en cours :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Id Produit</th>
                        <th scope="col">Désignation</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfStockOfTheYear as $salesofThe) {
                        echo '<tr>
                                <td> '.$salesofThe['id_produits'].'</td>
                                <td> '.$salesofThe['designation'].'</td>
                                <td> '.$salesofThe['SUM(quantite)'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>






    <div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Montant total des ventes HT par vendeur par mois :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Id Personnel</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesByEmployeesByMonth as $salesofTheMonth) {
                        echo '<tr>
                                <td> '.$salesofTheMonth['id_personnel'].'</td>
                                <td> '.$salesofTheMonth['prenom'].'</td>
                                <td> '.$salesofTheMonth['SUM(prix_ht)'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>





    
    <div class="container">
    <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">
        <p class="text-center mt-5">Montant total des ventes HT par vendeur sur l'année depuis le 01 janvier :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Id Personnel</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesByEmployeesByYear as $salesofTheYear) {
                        echo '<tr>
                                <td> '.$salesofTheYear['id_personnel'].'</td>
                                <td> '.$salesofTheYear['prenom'].'</td>
                                <td> '.$salesofTheYear['SUM(prix_ht)'].'</td>
                            </tr>';
                    }

                ?>
                </tbody>
            </table>
        </div>
    </div>



