


<div class="container">
    <div class="row">



            <div class="container col-sm-12 col-md-8 col-lg-4 border border-danger shadow-lg mb-5 mt-5">
                <div class="row">
                    <div class="text-center mt-4">
                        <h2 class="text-center">Ajouter un personnel</h2>
                            <form class="form-group" method="POST" action="Admin\createPersonnel">
                                <div class="d-grid gap-2 mx-auto mt-4">

                                    <input type="text" name="firstname" class="form-control text-center" placeholder="Prénom" required="required" autocomplete="off">
                                    <input type="text" name="role" class="form-control text-center" placeholder="Role : personnel" required="required" autocomplete="off">
                                    <input type="text" name="pass" class="form-control text-center" placeholder="Mot de passe" required="required" autocomplete="off">
                                    
                                </div>
                                <div class="d-grid gap-2 col-6 mx-auto mt-4 mb-4">
                                    <button type="submit" class="btn btn-danger">Valider</button>
                                </div>
                            </form>
                            
                    </div>
                </div>
            </div>
