<style>
    body {
        background-image: url('public/images/velo106.avif');
        background-size: cover;
        }
</style>


<!-- Modal de confirmation de suppression d'article, script modal.js -->
<div id="dialog-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialog-confirm-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dialog-confirm-title">Confirmation de la suppression</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sûr de vouloir supprimer cet élément ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirm-yes">Confirmer</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>





<div class="container">
    <div class="row">



            <div class="container col-sm-12 col-md-8 col-lg-4 border border-danger shadow-lg mb-5 mt-5 bg-white">
                <div class="row">
                    <div class="text-center mt-4">
                        <h2 class="text-center">Ajouter un client</h2>
                            <form class="form-group" method="POST" action="client\createClient">
                                <div class="d-grid gap-2 mx-auto mt-4">


                                    <input type="text" name="lastname" class="form-control text-center" placeholder="Nom" required="required" autocomplete="off">
                                    <input type="text" name="firstname" class="form-control text-center" placeholder="Prénom" required="required" autocomplete="off">
                                    <input type="text" name="adress1" class="form-control text-center" placeholder="Adresse" required="required" autocomplete="off">
                                    <input type="text" name="adress2" class="form-control text-center" placeholder="Complément d'adresse" required="required" autocomplete="off">
                                    <input type="text" name="postal_code" class="form-control text-center" placeholder="Code Postal" required="required" autocomplete="off">
                                    <input type="text" name="city" class="form-control text-center" placeholder="Ville" required="required" autocomplete="off">
                                    <input type="email" name="email" class="form-control text-center" placeholder="Email" required="required" autocomplete="off">
                                    <input type="text" name="phone" class="form-control text-center" placeholder="Téléphone" required="required" autocomplete="off">
                                    
                                </div>
                                <div class="d-grid gap-2 col-6 mx-auto mt-4 mb-4">
                                    <button type="submit" class="btn btn-danger">Valider</button>
                                </div>
                            </form>
                            
                    </div>
                </div>
            </div>





<div class="container">
        <div class="row mx-auto">
             <form class="form-group" action="Client\updateClient" method="POST">
                <table class="table mt-5 mb-5 border border-danger shadow-lg bg-white">
                    <thead>
                        <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Adresse</th>
                        <th scope="col">Complément d'adresse</th>
                        <th scope="col">Code postal</th>
                        <th scope="col">Ville</th>
                        <th scope="col">Email</th>
                        <th scope="col">Téléphone</th>
                        <th scope="col">Supprimer</th>
                        </tr>
                    </thead>

<?php
$ii = 0;
foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                        <td><input type="text" class="form-control" name="field['.$ii.'][id_client]" value="'.$res['id'].'" readonly="readonly"/></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][lastname]" value="'.$res['nom'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][firstname]" value="'.$res['prenom'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][adress1]" value="'.$res['adresse1'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][adress2]" value="'.$res['adresse2'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][postal_code]" value="'.$res['code_postal'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][city]" value="'.$res['ville'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][email]" value="'.$res['email'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][phone]" value="'.$res['telephone'].'"></td>
                        <td><a class="confirmModal btn btn-secondary mb-3 form-control" href="Client/deleteClient/'.$res['id'].'" ><i class="bi bi-trash3"></i></a></td>
                    </tr>

                </tbody>
               
            ';
++$ii;
}
?>

            </table>
                <input type="submit" class="form-control mb-5 bg-danger" value="Enregistrer les modifications">
        </form>
    </div>
</div> 


    <!-- Modal de suppression -->
    <script src="./public/modal.js"></script>

  
