


<div class="container">
    <div class="row">



            <div class="container col-sm-12 col-md-8 col-lg-4 border border-danger shadow-lg mb-5 mt-5">
                <div class="row">
                    <div class="text-center mt-4">
                        <h2 class="text-center">Ajouter un client</h2>
                            <form class="form-group" method="POST" action="client\createClient">
                                <div class="d-grid gap-2 mx-auto mt-4">


                                    <input type="text" name="lastname" class="form-control text-center" placeholder="Nom" required="required" autocomplete="off">
                                    <input type="text" name="firstname" class="form-control text-center" placeholder="Prénom" required="required" autocomplete="off">
                                    <input type="text" name="adress1" class="form-control text-center" placeholder="Adresse" required="required" autocomplete="off">
                                    <input type="text" name="adress2" class="form-control text-center" placeholder="Complément d'adresse" required="required" autocomplete="off">
                                    <input type="text" name="postal_code" class="form-control text-center" placeholder="Code Postal" required="required" autocomplete="off">
                                    <input type="text" name="city" class="form-control text-center" placeholder="Ville" required="required" autocomplete="off">
                                    <input type="text" name="email" class="form-control text-center" placeholder="Email" required="required" autocomplete="off">
                                    <input type="text" name="phone" class="form-control text-center" placeholder="Téléphone" required="required" autocomplete="off">
                                    
                                </div>
                                <div class="d-grid gap-2 col-6 mx-auto mt-4 mb-4">
                                    <button type="submit" class="btn btn-danger">Valider</button>
                                </div>
                            </form>
                            
                    </div>
                </div>
            </div>
