<style>
    body {
        background-image: url('public/images/velo108.avif');
        background-size: cover;
        }
</style>


<!-- Modal de confirmation de suppression d'article, script modal.js -->
<div id="dialog-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialog-confirm-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dialog-confirm-title">Confirmation de la suppression</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sûr de vouloir supprimer cet élément ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirm-yes">Confirmer</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>


<?php
    if(!empty($_SESSION['id']) && ($_SESSION['role'] == "boss")){
?>

    
<div class="container">
    <div class="row">

            <div class="container col-sm-12 col-md-8 col-lg-4 border border-danger shadow-lg mb-5 mt-5 bg-white">
                <div class="row">
                    <div class="text-center mt-4">
                        <h2 class="text-center">Ajouter un produit</h2>
                            <form class="form-group" method="POST" action="Stock\createStock">
                                <div class="d-grid gap-2 mx-auto mt-4">


                                    <input type="text" name="designation" class="form-control text-center" placeholder="Dénomination de l'article" required="required" autocomplete="off">
                                    <input type="text" name="reference" class="form-control text-center" placeholder="Réf en 2 lettres ex: VC" required="required" autocomplete="off">
                                    <input type="text" name="price_ht" class="form-control text-center" placeholder="Prix HT ex: 35.20" required="required" autocomplete="off">
                                    <input type="text" name="stock" class="form-control text-center" placeholder="Stock" required="required" autocomplete="off">
                                    <input type="text" name="alerte" class="form-control text-center" placeholder="Stock_alerte" required="required" autocomplete="off">
                                    <input type="text" name="id_tva" class="form-control text-center" placeholder="TVA appliquée ex: 1.2" required="required" autocomplete="off">
                                    
                                </div>
                                <div class="d-grid gap-2 col-6 mx-auto mt-4 mb-4">
                                    <button type="submit" class="btn btn-danger">Valider</button>
                                </div>
                            </form>
                            
                    </div>
                </div>
            </div>
                 
    </div>
</div>



        
    <div class="container">
        <div class="row mx-auto">

            <form class="form-group" action="Stock\updateProduit" method="POST">

                <table class="table mt-5 mb-5 border border-danger shadow-lg bg-white">
                    <thead>
                        <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Désignation</th>
                        <th scope="col">Référence</th>
                        <th scope="col">Prix_HT</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Stock_alerte</th>
                        <th scope="col">Taux_TVA</th>
                        <th scope="col">Supprimer</th>
                        </tr>
                    </thead>

<?php
$ii =0;
foreach($result as $res){

echo '
    <tbody>
        <tr '.($res->isAlerteStock() ? 'class="bg-danger"' : '').'>
            <td><input type="text" class="form-control" name="field['.$ii.'][id_produit]" value="'.$res->getId_produit().'" readonly="readonly"/></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][designation]" value="'.$res->getDesignation().'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][reference]" value="'.$res->getReference().'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][price_ht]" value="'.$res->getPrixHT().'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][stock]" value="'.$res->getStock().'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][alerte]" value="'.$res->getStock_alerte().'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][id_tva]" value="'.$res->getTva().'"></td> 
            <td><a class="confirmModal btn btn-secondary mb-3 form-control" href="Stock/deleteProduit/'.$res->getId_produit().'" ><i class="bi bi-trash3"></i></a></td>
        </tr>
    </tbody>
';
++$ii;
}
?>

                </table>
                 <input type="submit" class="form-control mb-5 bg-danger" value="Enregistrer les modifications">
            </form>

        </div>
    </div>



<?php
}else{ echo"<h4 class='text-center border border-danger shadow-lg mt-5 mb-3 bg-white'>Vous n'avez pas les droits pour accéder à cette page</h4>";
  
    }
?>


    <!-- Modal de suppression -->
    <script src="./public/modal.js"></script>

  