
<!-- Modal de confirmation de suppression d'article, script modal.js -->
<div id="dialog-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialog-confirm-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dialog-confirm-title">Confirmation de la suppression</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sûr de vouloir supprimer cet élément ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirm-yes">Confirmer</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>




<div class="container">
    <div class="row">



            <div class="container col-sm-12 col-md-8 col-lg-4 border border-danger shadow-lg mb-5 mt-5">
                <div class="row">
                    <div class="text-center mt-4">
                        <h2 class="text-center">Ajouter un personnel</h2>
                            <form class="form-group" method="POST" action="Admin\createPersonnel">
                                <div class="d-grid gap-2 mx-auto mt-4">

                                    <input type="text" name="firstname" class="form-control text-center" placeholder="Prénom" required="required" autocomplete="off">
                                    <input type="text" name="role" class="form-control text-center" placeholder="Role : personnel" required="required" autocomplete="off">
                                    <input type="text" name="pass" class="form-control text-center" placeholder="Mot de passe" required="required" autocomplete="off">
                                    
                                </div>
                                <div class="d-grid gap-2 col-6 mx-auto mt-4 mb-4">
                                    <button type="submit" class="btn btn-danger">Valider</button>
                                </div>
                            </form>
                            
                    </div>
                </div>
            </div>






    <div class="container">
        <div class="row mx-auto">

            <form class="form-group" action="Admin\updatePersonnel" method="POST">

                <table class="table mt-5 mb-5 border border-danger shadow-lg">
                    <thead>
                        <tr>
                        <th scope="col">Personnel</th>
                        <th scope="col">Role</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Supprimer</th>
                        </tr>
                    </thead>

<?php
$ii = 0;
foreach($result as $res){

echo '
    <tbody>
        <tr>
            <td><input type="text" class="form-control" name="field['.$ii.'][id_personnel]" value="'.$res['id'].'" readonly="readonly"/>
            <td><input type="text" class="form-control" name="field['.$ii.'][role]" value="'.$res['id_role'].'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][firstname]" value="'.$res['prenom'].'"></td>
            <td><a class="confirmModal btn btn-secondary mb-3 form-control" href="Admin/deletePersonnel/'.$res['id'].'" ><i class="bi bi-trash3"></i></a></td>
        </tr>
    </tbody>
';
++$ii;
}
?>

                </table>
                 <input type="submit" class="form-control mb-5 bg-danger" value="Enregistrer">
            </form>

        </div>
    </div>



    
    <!-- TODO script public .. ne marche pas -->
    <!-- <script src="../public/modal.js"></script> -->

    <script type="text/javascript">

    $(document).ready(function() {
  var theHREF;

  $('#dialog-confirm').on('show.bs.modal', function (event) {
    var modal = $(this);
    modal.find('.modal-body p').text('Etes-vous sûr de vouloir supprimer cet élément ?');
    modal.find('#confirm-yes').click(function() {
      modal.modal('hide');
      window.setTimeout(function(){
        window.location.href = theHREF;
      }, 100);
    });
  });

  $("a.confirmModal").click(function(e) {
    e.preventDefault();
    theHREF = $(this).attr("href");
    $('#dialog-confirm').modal('show');
  });
});

</script>
