


    <div class="container">
        <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">

            <table class="table mt-5 mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                    <th scope="col">Personnel</th>
                    <th scope="col">Role</th>
                    <th scope="col">Prénom</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                    <td>'.$res['id'].'</td>
                    <td>'.$res['id_role'].'</td>
                    <td>'.$res['prenom'].'</td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>

                
        </div>
    </div>



