


<div class="container">
        <div class="row mx-auto">

            <table class="table mt-5 mb-5 border border-danger shadow-lg text-center">
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Complément d'adresse</th>
                    <th scope="col">Code postal</th>
                    <th scope="col">Ville</th>
                    <th scope="col">Email</th>
                    <th scope="col">Téléphone</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                    <td>'.$res['id'].'</td>
                    <td>'.$res['nom'].'</td>
                    <td>'.$res['prenom'].'</td>
                    <td>'.$res['adresse1'].'</td>
                    <td>'.$res['adresse2'].'</td>
                    <td>'.$res['code_postal'].'</td>
                    <td>'.$res['ville'].'</td>
                    <td>'.$res['email'].'</td>
                    <td>'.$res['telephone'].'</td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>
    </div>
</div> 


