<style>
    body {
        background-image: url('public/images/velo20.jpg');
        background-size: cover;
        }
</style>


<?php
    if(!empty($_SESSION['id']) && ($_SESSION['role'] == "boss")){
?>


    <div class="container">
        <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">

            <table class="table mt-5 mb-5 border border-danger shadow-lg text-center">
                <thead>
                    <tr class="bg-white">
                    <th scope="col">Personnel</th>
                    <th scope="col">Role</th>
                    <th scope="col">Prénom</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr class="bg-white">
                    <td>'.$res['id'].'</td>
                    <td>'.$res['id_role'].'</td>
                    <td>'.$res['prenom'].'</td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>

                
        </div>
    </div>



    <?php
}else{ echo"<h4 class='text-center border border-danger shadow-lg mt-5 mb-3 bg-white'>Vous n'avez pas les droits pour accéder à cette page</h4>";
  
    }
?>