


<div class="container">
        <div class="row mx-auto">

            <table class="table mt-5 mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Date_Facture</th>
                    <th scope="col">Prix_HT</th>
                    <th scope="col">Prix_TTC</th>
                    <th scope="col">Id_Client</th>
                    <th scope="col">Nom_Client</th>
                    <th scope="col">ID_Personnel</th>
                    <th scope="col">Prenom_Personnel</th>
                    <th scope="col">Voir_facture</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                    <td>'.$res['factID'].'</td>
                    <td>'.$res['dateFact'].'</td>
                    <td>'.$res['prix_ht'].'</td>
                    <td>'.$res['prix_ttc'].'</td>
                    <td>'.$res['id_client'].'</td>
                    <td>'.$res['nom'].'</td>
                    <td>'.$res['id_personnel'].'</td>
                    <td>'.$res['prenom'].'</td>
                    <td><i class="bi bi-filetype-pdf"></i></td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>
    </div>
</div> 


