

<!-- Modal de confirmation de suppression d'article, script modal.js -->
<div id="dialog-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialog-confirm-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dialog-confirm-title">Confirmation de la suppression</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sûr de vouloir supprimer cet élément ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirm-yes">Confirmer</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>




<div class="container">
        <div class="row mx-auto">

            <table class="table mt-5 mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Complément d'adresse</th>
                    <th scope="col">Code postal</th>
                    <th scope="col">Ville</th>
                    <th scope="col">Email</th>
                    <th scope="col">Téléphone</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                    <td>'.$res['id'].'</td>
                    <td>'.$res['nom'].'</td>
                    <td>'.$res['prenom'].'</td>
                    <td>'.$res['adresse1'].'</td>
                    <td>'.$res['adresse2'].'</td>
                    <td>'.$res['code_postal'].'</td>
                    <td>'.$res['ville'].'</td>
                    <td>'.$res['email'].'</td>
                    <td>'.$res['telephone'].'</td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>
    </div>
</div> 




<div class="container">
        <div class="row mx-auto">
             <form class="form-group" action="Client\updateClient" method="POST">
                <table class="table mt-5 mb-5 border border-danger shadow-lg">
                    <thead>
                        <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Adresse</th>
                        <th scope="col">Complément d'adresse</th>
                        <th scope="col">Code postal</th>
                        <th scope="col">Ville</th>
                        <th scope="col">Email</th>
                        <th scope="col">Téléphone</th>
                        <th scope="col">Supprimer</th>
                        </tr>
                    </thead>

<?php
$ii = 0;
foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                        <td><input type="text" class="form-control" name="field['.$ii.'][id_client]" value="'.$res['id'].'" readonly="readonly"/></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][lastname]" value="'.$res['nom'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][firstname]" value="'.$res['prenom'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][adress1]" value="'.$res['adresse1'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][adress2]" value="'.$res['adresse2'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][postal_code]" value="'.$res['code_postal'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][city]" value="'.$res['ville'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][email]" value="'.$res['email'].'"></td>
                        <td><input type="text" class="form-control" name="field['.$ii.'][phone]" value="'.$res['telephone'].'"></td>
                        <td><a class="confirmModal btn btn-secondary mb-3 form-control" href="Client/deleteClient/'.$res['id'].'" ><i class="bi bi-trash3"></i></a></td>
                    </tr>

                </tbody>
               
            ';
++$ii;
}
?>

            </table>
                <input type="submit" class="form-control mb-5 bg-danger" value="Enregistrer les modifications">
        </form>
    </div>
</div> 


        



    <!-- TODO script public .. ne marche pas -->
    <!-- <script src="../public/modal.js"></script> -->

    <script type="text/javascript">

    $(document).ready(function() {
  var theHREF;

  $('#dialog-confirm').on('show.bs.modal', function (event) {
    var modal = $(this);
    modal.find('.modal-body p').text('Etes-vous sûr de vouloir supprimer cet élément ?');
    modal.find('#confirm-yes').click(function() {
      modal.modal('hide');
      window.setTimeout(function(){
        window.location.href = theHREF;
      }, 100);
    });
  });

  $("a.confirmModal").click(function(e) {
    e.preventDefault();
    theHREF = $(this).attr("href");
    $('#dialog-confirm').modal('show');
  });
});

</script>
