
<style>
    body {
        background-image: url('public/images/velo15.jpg');
        background-size: cover;
        }
</style>




<div class="container">
        <div class="row mx-auto">

            <table class="table mt-5 mb-5 border border-danger shadow-lg text-center">
                <thead>
                    <tr class="bg-white">
                    <th scope="col">ID</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Complément d'adresse</th>
                    <th scope="col">Code postal</th>
                    <th scope="col">Ville</th>
                    <th scope="col">Email</th>
                    <th scope="col">Téléphone</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr class="bg-white">
                    <td>'.$res['id'].'</td>
                    <td>'.$res['nom'].'</td>
                    <td>'.$res['prenom'].'</td>
                    <td>'.$res['adresse1'].'</td>
                    <td>'.$res['adresse2'].'</td>
                    <td>'.$res['code_postal'].'</td>
                    <td>'.$res['ville'].'</td>
                    <td>'.$res['email'].'</td>
                    <td>'.$res['telephone'].'</td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>
    </div>
</div> 


