<style>
    body {
        background-image: url('public/images/velo22.jpg');
        background-size: cover;
        }
</style>


<div class="container">
        <div class="row mx-auto">

            <table class="table mt-5 mb-5 border border-danger shadow-lg text-center">
                <thead>
                    <tr class="bg-white">
                    <th scope="col">ID</th>
                    <th scope="col">Date_Facture</th>
                    <th scope="col">Prix_HT</th>
                    <th scope="col">Prix_TTC</th>
                    <th scope="col">ID_Client</th>
                    <th scope="col">Nom_Client</th>
                    <th scope="col">Prénom_Client</th>
                    <th scope="col">ID_Personnel</th>
                    <th scope="col">Prénom_Personnel</th>
                    <th scope="col">Voir_facture</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr class="bg-white">
                    <td>'.$res['idFact'].'</td>
                    <td>'.$res['dateFact'].'</td>
                    <td>'.$res['prix_ht'].'</td>
                    <td>'.$res['prix_ttc'].'</td>
                    <td>'.$res['id_client'].'</td>
                    <td>'.$res['nom'].'</td>
                    <td>'.$res['12'].'</td>
                    <td>'.$res['id_personnel'].'</td>
                    <td>'.$res['prenom'].'</td>
                    <td><a href="#" id="funct" onclick="finalInv('.$res['idFact'].')" class="" data-bs-toggle="modal" data-bs-target="#Facture"><i class="bi bi-search" style="font-size: 18px;"></i></a></td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>
    </div>
</div> 

<script>

//Fonction pour qu'au click sur un produit par sa designation/id, affiche la quantité présente dans la bdd 
function finalInv(idFact) {
    window.location.href = "Invoice/finalyInvoices/"+idFact;
    
}



function finalInvs(idFact) {
    const xhttp = new XMLHttpRequest();
    xhttp.onload = function() {
        document.getElementById('Facture').innerHTML = this.responseText;
    }
    xhttp.open("GET", "/velo/Invoice/finalyInvoices/"+idFact, true);
    xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
    xhttp.send();
    
}



</script>



