
<!-- Modal de confirmation de suppression d'article, script modal.js -->
<div id="dialog-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialog-confirm-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dialog-confirm-title">Confirmation de la suppression</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sûr de vouloir supprimer cet élément ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirm-yes">Confirmer</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>




    <div class="container">
        <div class="row mx-auto col-lg-4 col-md-8 col-sm-12">

            <table class="table mt-5 mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                    <th scope="col">Personnel</th>
                    <th scope="col">Role</th>
                    <th scope="col">Prénom</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr>
                    <td>'.$res['id'].'</td>
                    <td>'.$res['id_role'].'</td>
                    <td>'.$res['prenom'].'</td>
                    </tr>

                </tbody>
               
            ';
}
?>

            </table>

                
        </div>
    </div>




    <div class="container">
        <div class="row mx-auto">

            <form class="form-group" action="Admin\updatePersonnel" method="POST">

                <table class="table mt-5 mb-5 border border-danger shadow-lg">
                    <thead>
                        <tr>
                        <th scope="col">Personnel</th>
                        <th scope="col">Role</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Supprimer</th>
                        </tr>
                    </thead>

<?php
$ii = 0;
foreach($result as $res){

echo '
    <tbody>
        <tr>
            <td><input type="text" class="form-control" name="field['.$ii.'][id_personnel]" value="'.$res['id'].'" readonly="readonly"/>
            <td><input type="text" class="form-control" name="field['.$ii.'][role]" value="'.$res['id_role'].'"></td>
            <td><input type="text" class="form-control" name="field['.$ii.'][firstname]" value="'.$res['prenom'].'"></td>
            <td><a class="confirmModal btn btn-secondary mb-3 form-control" href="Admin/deletePersonnel/'.$res['id'].'" ><i class="bi bi-trash3"></i></a></td>
        </tr>
    </tbody>
';
++$ii;
}
?>

                </table>
                 <input type="submit" class="form-control mb-5 bg-danger" value="Enregistrer">
            </form>

        </div>
    </div>



    
    <!-- TODO script public .. ne marche pas -->
    <!-- <script src="../public/modal.js"></script> -->

    <script type="text/javascript">

    $(document).ready(function() {
  var theHREF;

  $('#dialog-confirm').on('show.bs.modal', function (event) {
    var modal = $(this);
    modal.find('.modal-body p').text('Etes-vous sûr de vouloir supprimer cet élément ?');
    modal.find('#confirm-yes').click(function() {
      modal.modal('hide');
      window.setTimeout(function(){
        window.location.href = theHREF;
      }, 100);
    });
  });

  $("a.confirmModal").click(function(e) {
    e.preventDefault();
    theHREF = $(this).attr("href");
    $('#dialog-confirm').modal('show');
  });
});

</script>
