

    <div class="container">
        <div class="row mx-auto col-sm-12 col-md-9 col-lg-7">

            <table class="table mt-5 mb-5 border border-danger shadow-lg text-center">
                <thead>
                    <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Désignation</th>
                    <th scope="col">Référence</th>
                    <th scope="col">Prix_HT</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Stock_alerte</th>
                    <th scope="col">Taux_TVA</th>
                    </tr>
                </thead>

<?php

foreach($result as $res){

echo    '

                <tbody>
                    <tr '.($res->isAlerteStock() ? 'class="bg-danger"' : '').'>
                        <td>'.$res->getId_Produit().'</td>
                        <td>'.$res->getDesignation().'</td>
                        <td>'.$res->getReference().'</td>
                        <td>'.$res->getPrixHT().'</td>
                        <td>'.$res->getStock().'</td>
                        <td>'.$res->getStock_alerte().'</td>
                        <td>'.$res->getTva().'</td>
                    </tr>
                </tbody>
               
            ';
}
?>

            </table>
                
        </div>
    </div>

