

<?php
    if(!empty($_SESSION["id"]) && $_SESSION["role"] == 'personnel') {
?>


    <div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Récapitulatif mensuel des ventes du mois pour <?php echo $_SESSION['prenom']?> :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">ID_Facture</th>
                        <th scope="col">Date</th>
                        <th scope="col">Total_ht</th>
                        <th scope="col">Total_ttc</th>
                        <th scope="col">Id_client</th>
                        <th scope="col">Id_personnel</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfTheMonth as $saleso) {
                        echo '<tr>
                                <td> '.$saleso['id'].'</td>
                                <td> '.$saleso['dateFact'].'</td>
                                <td> '.$saleso['prix_ht'].'</td>
                                <td> '.$saleso['prix_ttc'].'</td>
                                <td> '.$saleso['id_client'].'</td>
                                <td> '.$saleso['id_personnel'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>




    

    <div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Récapitulatif mensuel des ventes de l'année pour <?php echo $_SESSION['prenom']?> :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">ID_Facture</th>
                        <th scope="col">Date</th>
                        <th scope="col">Total_ht</th>
                        <th scope="col">Total_ttc</th>
                        <th scope="col">Id_client</th>
                        <th scope="col">Id_personnel</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfTheYear as $sale) {
                        echo '<tr>
                                <td> '.$sale['id'].'</td>
                                <td> '.$sale['dateFact'].'</td>
                                <td> '.$sale['prix_ht'].'</td>
                                <td> '.$sale['prix_ttc'].'</td>
                                <td> '.$sale['id_client'].'</td>
                                <td> '.$sale['id_personnel'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>


<?php
}
?>

    

 
<?php
if(!empty($_SESSION["id"]) && $_SESSION["role"] == 'boss') {
?>

    

<div class="container">
<div class="row mx-auto">
    <p class="text-center fw-bold mt-5">Récapitulatif mensuel des ventes du mois pour <?php echo $_SESSION['prenom']?> :</p>
        <table class="table mb-5 border border-danger shadow-lg">
            <thead>
                <tr>
                    <th scope="col">ID_Facture</th>
                    <th scope="col">Date</th>
                    <th scope="col">Total_ht</th>
                    <th scope="col">Total_ttc</th>
                    <th scope="col">Id_client</th>
                    <th scope="col">Id_personnel</th>
                </tr>
            </thead>
            <tbody>
        
            <?php
                // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                foreach ($SalesOfTheMonth as $saleso) {
                    echo '<tr>
                            <td> '.$saleso['id'].'</td>
                            <td> '.$saleso['dateFact'].'</td>
                            <td> '.$saleso['prix_ht'].'</td>
                            <td> '.$saleso['prix_ttc'].'</td>
                            <td> '.$saleso['id_client'].'</td>
                            <td> '.$saleso['id_personnel'].'</td>
                        </tr>';
                }
            ?>
            </tbody>
        </table>
    </div>
</div>






<div class="container">
<div class="row mx-auto">
    <p class="text-center fw-bold mt-5">Récapitulatif mensuel des ventes de l'année pour <?php echo $_SESSION['prenom']?> :</p>
        <table class="table mb-5 border border-danger shadow-lg">
            <thead>
                <tr>
                    <th scope="col">ID_Facture</th>
                    <th scope="col">Date</th>
                    <th scope="col">Total_ht</th>
                    <th scope="col">Total_ttc</th>
                    <th scope="col">Id_client</th>
                    <th scope="col">Id_personnel</th>
                </tr>
            </thead>
            <tbody>
        
            <?php
                // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                foreach ($SalesOfTheYear as $sale) {
                    echo '<tr>
                            <td> '.$sale['id'].'</td>
                            <td> '.$sale['dateFact'].'</td>
                            <td> '.$sale['prix_ht'].'</td>
                            <td> '.$sale['prix_ttc'].'</td>
                            <td> '.$sale['id_client'].'</td>
                            <td> '.$sale['id_personnel'].'</td>
                        </tr>';
                }
            ?>
            </tbody>
        </table>
    </div>
</div>




<?php
    foreach($salesOfTheDay as $sal)
        echo' 
        <div class ="container border border-danger mt-5 mb-5"
            <div class="row">
                <p class="text-center fw-bold mt-2 mb-2">Le total des ventes du jour est : '.$sal['Total'].' €</p>
            </div>
        </div>
        ';
?>





<div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Récapitulatif mensuel des ventes par produit :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">ID_Produit</th>
                        <th scope="col">Désignation</th>
                        <th scope="col">Quantité_vendue</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($salesOfStockOfTheMonth as $sales) {
                        echo '<tr>
                                <td> '.$sales['id_produits'].'</td>
                                <td> '.$sales['designation'].'</td>
                                <td> '.$sales['SUM(quantite)'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>





    
<div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Total TVA collecté par mois :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Total_ht</th>
                        <th scope="col">Total_ttc</th>
                        <th scope="col">TVA_à_reverser</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfStockOfTheMonthAndShowTVA as $salesof) {
                        echo '<tr>
                                <td> '.$salesof['total_ht'].'</td>
                                <td> '.$salesof['total_ttc'].'</td>
                                <td> '.$salesof['TVA_a_reverser'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>





    
    
<div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Etat cumulé des ventes par produit depuis le premier janvier de l’année en cours :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Id_Produit</th>
                        <th scope="col">Désignation</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesOfStockOfTheYear as $salesofThe) {
                        echo '<tr>
                                <td> '.$salesofThe['id_produits'].'</td>
                                <td> '.$salesofThe['designation'].'</td>
                                <td> '.$salesofThe['SUM(quantite)'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>






    <div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Montant total des ventes HT par vendeur par mois :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Id_Personnel</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesByEmployeesByMonth as $salesofTheMonth) {
                        echo '<tr>
                                <td> '.$salesofTheMonth['id_personnel'].'</td>
                                <td> '.$salesofTheMonth['prenom'].'</td>
                                <td> '.$salesofTheMonth['SUM(prix_ht)'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>





    
    <div class="container">
    <div class="row mx-auto">
        <p class="text-center fw-bold mt-5">Montant total des ventes HT par vendeur sur l'année depuis le 01 janvier :</p>
            <table class="table mb-5 border border-danger shadow-lg">
                <thead>
                    <tr>
                        <th scope="col">Id_Personnel</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
            
                <?php
                    // Boucler sur les résultats et afficher chaque ligne dans un tableau HTML
                    foreach ($SalesByEmployeesByYear as $salesofTheYear) {
                        echo '<tr>
                                <td> '.$salesofTheYear['id_personnel'].'</td>
                                <td> '.$salesofTheYear['prenom'].'</td>
                                <td> '.$salesofTheYear['SUM(prix_ht)'].'</td>
                            </tr>';
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>


<?php
}
?>
